module.exports = {
  ROLES: {
    DEO: 'DEO',
    VERIFIER: 'VERIFIER',
    DISTRICT_OFFICER: 'DISTRICT_OFFICER',
    STATE_ADMIN: 'STATE_ADMIN',
    SUPER_ADMIN: 'SUPER_ADMIN',
  },
  ALL_ROLES: ['DEO', 'VERIFIER', 'DISTRICT_OFFICER', 'STATE_ADMIN', 'SUPER_ADMIN'],

  DOCUMENT_STATUS: {
    UPLOADED: 'UPLOADED',
    PROCESSING: 'PROCESSING',
    PROCESSED: 'PROCESSED',
    FAILED: 'FAILED',
    OCR_FAILED: 'OCR_FAILED',
  },

  RECORD_STATUS: {
    EXTRACTED: 'EXTRACTED',
    NEEDS_VERIFICATION: 'NEEDS_VERIFICATION',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    VALIDATED: 'VALIDATED',
    PUBLISHED: 'PUBLISHED',
    REJECTED: 'REJECTED',
    ARCHIVED: 'ARCHIVED',
  },

  TASK_STATUS: {
    OPEN: 'OPEN',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
  },

  TASK_PRIORITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    URGENT: 'URGENT',
  },

  LAND_CLASSIFICATIONS: [
    'AGRICULTURAL_IRRIGATED',
    'AGRICULTURAL_UNIRRIGATED',
    'RESIDENTIAL',
    'COMMERCIAL',
    'INDUSTRIAL',
    'FOREST',
    'GOVERNMENT_WASTELAND',
    'PASTURE_GRAZING',
    'WATER_BODY',
  ],

  AREA_UNITS: ['acres', 'hectares', 'bigha', 'sq_meters', 'sq_yards', 'guntha'],

  OWNERSHIP_TYPES: ['INDIVIDUAL', 'JOINT', 'GOVERNMENT', 'COMMUNITY', 'TRUST_TEMPLE', 'DISPUTED'],

  AUDIT_ACTIONS: {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    STATUS_CHANGE: 'STATUS_CHANGE',
    APPROVE: 'APPROVE',
    REJECT: 'REJECT',
    PUBLISH: 'PUBLISH',
    EXPORT: 'EXPORT',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    DELETE: 'DELETE',
    VERIFY: 'VERIFY',
    GEO_UPDATE: 'GEO_UPDATE',
  },

  API_SCOPES: ['read:records', 'read:dashboard', 'read:pii', 'read:gis'],

  DEFAULT_THRESHOLDS: {
    OVERALL_CONFIDENCE: 80,
    FIELD_CONFIDENCE: 60,
  },
};
